version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    user: root
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false

  dev_app:
    build: .
    environment:
      - ENV_NAME=DEV
    ports:
      - "3100:3000"
    depends_on:
      - jenkins

  qa_app:
    build: .
    environment:
      - ENV_NAME=QA
    ports:
      - "3200:3000"

  uat_app:
    build: .
    environment:
      - ENV_NAME=UAT
    ports:
      - "3300:3000"

volumes:
  jenkins_home:
